version: 2

registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/

updates:
  - package-ecosystem: maven
    directory: "/"
    registries:
      - maven-central
    schedule:
      interval: daily
