version: ~> 1.0

language: java

addons:
  sonarcloud:
    organization: "simplify4u"


jobs:
  include:
      - name: "jdk8 - linux"
        jdk: openjdk8
        os: linux
        script:
          - echo "SONARQUBE_SCANNER_PARAMS=$SONARQUBE_SCANNER_PARAMS"
          - mvn help:help
          - env

