name: Build - New JDK

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:

  build-18-zulu:
    name: 18 zulu
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18"]'
      java-dist-matrix: '["zulu"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-18-ea-zulu:
    needs: build-18-zulu
    name: 18-ea zulu
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18-ea"]'
      java-dist-matrix: '["zulu"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-18-temurin:
    needs: build-18-ea-zulu
    name: 18 temurin
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18"]'
      java-dist-matrix: '["temurin"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-18-ea-temurin:
    needs: build-18-temurin
    name: 18-ea temurin
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18-ea"]'
      java-dist-matrix: '["temurin"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-18-liberica:
    needs: build-18-ea-temurin
    name: 18 liberica
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18"]'
      java-dist-matrix: '["liberica"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-18-ea-liberica:
    needs: build-18-liberica
    name: 18-ea liberica
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18-ea"]'
      java-dist-matrix: '["liberica"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}
