name: Build - New JDK

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:

  build:
    name: build 18
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["18", "18-ea"]'
      java-dist-matrix: '["zulu", "temurin", "liberica"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  verify-ok:
    name: OK
    needs: [ build ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - run: 'true'
        if: needs.build.statu == 'success'

      - run: 'false'
        if: needs.build.statu != 'success'
