name: Build - New JDK

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

  workflow_dispatch:

  schedule:
    - cron: '55 5 * * 5'

jobs:

  build-21:
    name: build 21
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["21"]'
      java-dist-matrix: '["zulu", "temurin", "liberica", "microsoft", "corretto", "semeru"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  build-22:
    needs: [ build-21 ]
    name: build 22
    uses: s4u/.github/.github/workflows/maven-build.yml@master
    with:
      java-matrix:  '["22-ea"]'
      java-dist-matrix: '["zulu", "temurin", "liberica", "microsoft", "corretto", "semeru"]'

    secrets:
      SIGN_KEY:       ${{ secrets.SIGN_KEY }}
      SIGN_KEY_PASS:  ${{ secrets.SIGN_KEY_PASS }}
      OSS_USER:       ${{ secrets.OSS_USER }}
      OSS_PASS:       ${{ secrets.OSS_PASS }}
      TECH_TOKEN:     ${{ secrets.TECH_TOKEN }}

  verify-ok:
    name: OK
    needs: [ build-21, build-22 ]
    if: always()
    runs-on: ubuntu-latest

    steps:
      - run: 'true'
        if: needs.build.result == 'success'

      - run: 'false'
        if: needs.build.result != 'success'
