name: Build Shared

on:
  push:
    branches:
      - 'master'
      - 'main'
    tags:
      - 'v*'

  schedule:
    - cron: '55 5 * * 5'

jobs:
  build:
    uses: s4u/.github/workflows/maven-build.yml@master
