name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: ./.github/actions/set-env-action
      with:
        name: "test_env"
        value: "test_value"
        test1: value1
        test.test2: value2
        test_test3_username: value3
        test_test3_passs: value4

    - uses: ./.github/actions/set-env-action
      with:
        name: "test2_env"
        value: ${{ secrets.TEST_SECRET }}

    - uses: ./.github/actions/set-env-action
      with:
        name: "test2_env"
        value: '[{"id": "test", "test22": "value22"}]'

    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'

    - run: env
    - run:  ls -la ~/.
    - run: mvn -V -B help:effective-settings
    - run:  ls -la ~/.
    - run:  ls -la ~/.m2/


  env-info:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
