name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/set-env-action
      with:
        name: "test_env"
        value: "test_value"
    - uses: ./.github/actions/set-env-action
      with:
        name: "test2_env"
        value: "test2_value"
    - run: env
