name: GitHub Pages

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - 'v*'

  pull_request:
    branches:
      - 'master'

jobs:
  build:
    name: Maven site

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key:          site-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: site-maven-

      - uses: s4u/maven-settings-action@v2
        with:
          sonatypeSnapshots: true
          properties: |
            [
              {"username": "git"},
              {"password": "${{ secrets.GITHUB_TOKEN }}"},
              {"scmpublish.pubScmUrl": "scm:git:${{ github.event.repository.url}}"}
            ]

      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Action"

      - name: Deploy Maven Site
        run: mvn site-deploy -Dscmpublish.dryRun=false
        if: github.repository_owner == 's4u' && startsWith( github.ref, 'refs/tags/') && github.event_name == 'push'

      - name: Test Maven Site
        run: mvn site
        if: startsWith( github.ref, 'refs/heads/')
