name: gh-pages

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        java: [8, 11, 13]
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: s4u/maven-settings-action@v2

      - run: mvn site-deploy
