name: hang test

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    tags:
      - 'v*'


jobs:

  test1:
    name: Build ${{ matrix.os }} with sleep ${{ matrix.sleep }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        sleep: [60, 120, 300]

    steps:
      - run: sleep ${{ matrix.sleep }}
        shell: bash

      - run: echo "sleep finish"

  test2:
    name: Build ${{ matrix.os }} with sleep ${{ matrix.sleep }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macOS-latest ]
        sleep: [60, 120, 300]

    steps:
      - run:  while sleep 60; do echo "=====[ $SECONDS seconds elapsed -- still running ]====="; done &

      - run: sleep ${{ matrix.sleep }}
        shell: bash

      - run: echo "sleep finish"
