name: Labels sync

on:
  workflow_dispatch:
    inputs:
      token:
        description: PAT Token to perform action
        default: ${{ github.token }}
        type: string

jobs:
  sync-label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - testing

    steps:
      - name: Sync labels on ${{ matrix.repo }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          REPO: ${{ matrix.repo }}
        with:
          github-token: ${{ inputs.token }}
          script: |
            const currentLabels = await github.rest.issues.listLabelsForRepo({
              owner: 's4u',
              repo: process.env.REPO
            });
            
            console.log(currentLabels);

