name: Labels sync

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: 'A GitHub token used to perform action'
        required: true

jobs:
  sync-label:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        repo:
          - testing


    steps:
      - name: Mask GitHub token
        run: echo "::add-mask::${{ inputs.token }}"

      - uses: actions/checkout@v3

      - name: Sync labels on ${{ matrix.repo }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          OWNER: 's4u'
          REPO: ${{ matrix.repo }}
        with:
          github-token: ${{ inputs.token }}
          script: |

            core.setSecret(core.getInput('github-token'));

            const labels = require('./.github/labels.js');

            console.log('Labels to update:');
            console.log(labels);
            
            console.log(process.env);
            
            const currentLabels = await github.rest.issues.listLabelsForRepo({
                owner: process.env.OWNER,
                repo: process.env.REPO
              });
            
            console.log('Current project labels:');
            console.log(currentLabels.data);

            
            for (const label of labels) {
              const currentLabel = currentLabels.data.find(({name}) => name == label.name);

              console.log('Label:');
              console.log(label);

              console.log('currentLabel:');
              console.log(currentLabel);
            
              if (!currentLabel) {
  
                console.log('Add label: ' + label.name);
                github.rest.issues.createLabel({
                  owner: process.env.OWNER,
                  repo: process.env.REPO,
                  ...label
                });
  
              } else if (label.color != currentLabel.color || label.description != currentLabel.description) {
                
                console.log('Update label: ' + label.name);
                github.rest.issues.updateLabel({
                  owner: process.env.OWNER,
                  repo: process.env.REPO,
                  ...label
                });
            
              } else {
                console.log('Label: ' + label.name + ' is up to date');
              }
            }
