name: Labels sync

on:
  workflow_dispatch:

jobs:
  sync-label:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - s4u/testing

    steps:
      - name: Sync labels on ${{ matrix.repo }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          REPO: ${{ matrix.repo }}
        with:
          script: |
            const currentLabels = await github.rest.issues.listLabelsForRepo({
              owner: context.repo.owner,
              repo: process.env.REPO
            });
            
            console.log(currentLabels);

