name: Labels sync

on:
  workflow_dispatch:
    inputs:
      token:
        type: string
        description: 'A GitHub token used to perform action - access token (classic) with repo'
        required: true

jobs:
  repos:
    name: Prepare repositories list
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.repo.outputs.matrix }}

    steps:
      - id: repo
        run: |
          {
            echo 'matrix<<EOF'          
            curl -s https://gitbox.apache.org/repositories.json | jq '.projects.maven.repositories | to_entries | sort_by(.key) | .[] | select(.value.description | contains("archived") | not) | .key' | jq -sc
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          
          cat "$GITHUB_OUTPUT"

  sync-label:
    runs-on: ubuntu-latest
    needs: repos
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        repo: ${{ fromJSON( needs.repos.outputs.matrix ) }}

    steps:
      - name: Mask GitHub token
        run: echo "::add-mask::$(jq -r '.inputs.token' $GITHUB_EVENT_PATH)"

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false

      - name: Sync labels on ${{ matrix.repo }}
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7
        env:
          OWNER: 's4u'
          REPO: ${{ matrix.repo }}
        with:
          github-token: ${{ inputs.token }}
          script: |
            const labels = require('./.github/labels.js');

            console.log('Labels to update:');
            console.log(labels);
