name: Pull Request Management

on:
  pull_request:
    types:
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted

jobs:
  env-info:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest

    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: List Reviews
        id: list-reviews
        uses: actions/github-script@v7
        with:
          script: |
            console.log(context);
            
            const query = `query($owner:String!, $name:String!, $number:Int!) {
              repository(name: $name, owner: $owner) {
                pullRequest(number: $number) {
                  title
                  reviewDecision
                  url
                }
              }
            }`;
            
            const variables = {
              owner: context.repo.owner,
              name: context.repo.repo,
              number: context.issue.number
            }
            
            const result = await github.graphql(query, variables)
            console.log(result)
            
            return result;

      - name: Review result
        run: echo "${{steps.list-reviews.outputs.result}}"

      - name: Current labels - ${{ join(github.event.pull_request.labels.*.name, ', ') }}
        run: "true"

      - name: Required labels missing
        if: >
          github.event.pull_request.draft == false &&
          !(
            contains(github.event.pull_request.labels.*.name, 'bug') ||
            contains(github.event.pull_request.labels.*.name, 'dependencies')
          )

        run: |
          echo "PR should have on of label: bug, dependencies"
          false

      - name: Check Milestone
        if: >
          github.event.pull_request.draft == false
        uses: actions/github-script@v7
        with:
          script: |            
            const milestones = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            console.log(milestones);
