name: pull_request_target

on:
  pull_request_target:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'refs/pull/${{ github.event.number }}/merge'

      - name: show files2
        run: |
          ls -l
          cat *.txt
          git log --graph --oneline -10

      - run: echo "PR ${{ github.event.number }} base ${{ github.event.base.ref }} branch ${{ github.event.head.label }}"

      - name: Test secret
        env:
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$TEST_SECRET" | wc
          echo "$TEST_SECRET" | md5sum

      - name: Dump Env
        run: env

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
