name: test

on:
  push:

jobs:
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ github.token }}" -i https://api.github.com/repos/${{ github.repository }}
          curl -H "Authorization: token ${{ github.token }}" -i https://api.github.com/orgs/${{ github.event.organization.login }}
