name: test

on:
  push:
  pull_request:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker1
        uses: ./.github/actions/docker1
  test2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -H "Authorization: token ${{ github.token }}" -H "Accept: application/vnd.github.groot-preview+json" -i https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls
