name: workflow run

on:
  workflow_run:
    workflows: ["pull_request"]
    types:
      - completed
      - requested

jobs:
  env-info:

    runs-on: ubuntu-latest

    steps:
      - name: Dump Env
        run: env
        shell: bash

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
